### PR TITLE
Fix callback closure scope

### PR DESCRIPTION
**Pull request by peter-gribanov**
I catch error:

```
Uncaught TypeError: Cannot read property 'eval_js' of undefined
    at set_content_async
    at XMLHttpRequest.s.onreadystatechange
```

The problem is that the closure scope is lost.

### CODE REVIEW

**Comment by peter-gribanov** [comment]
In `buffered` mode this error also exists:

```
Uncaught TypeError: this.eval_js is not a function
    at show_buffered_content
```

**Comment by peter-gribanov** [comment]
See #61 for more details

**Comment by peter-gribanov** [comment]
@mnot ping

**Comment by mnot** [comment]
Sorry; thanks.

**Pull request merged**
