### PR TITLE
Refactor to custom element h-include

### PR DESCRIPTION
**Pull request by gustafnk**
* Remove addDOMLoadEvent polyfill
* Move code from `run` to custom element `createdCallback`
* Move `refresh` to custom element
* Keep rest of code as before
* Use key/value cache in get_meta, since it's run on every `createdCallback`

### CODE REVIEW

**Comment by gustafnk** [comment]
Strange, tests are not run on Travis, but they works on my machine. And I haven't changed how tests are run. I'll investigate...

Any clues?

**Comment by gustafnk** [comment]
Ok, so the tests pass now. Don't know exactly why, let's keep an eye open.

Ready for review @mnot.

**Comment by mnot** [comment]
Cool stuff. However, there's lots of content out there that depends on the current syntax, and making this change will break it. 

So, I think this would be better as a separate package. Happy to link to it in docs so people can discover it, if you like.

**Comment by gustafnk** [comment]
Ok, thanks Mark :)

Would you like another PR where I keep the old code (backwards compatible) but add the custom element integration as well? I.e. supporting both the XML element syntax and the custom element syntax.

I don't think it would be super hard to code, but it's extra code to maintain and test, of course.

**Comment by mnot** [comment]
I think it's probably best to make it separate; that way, you can evolve as needed. Again, happy to advertise for you.

**Comment by gustafnk** [comment]
I've created a separate repository at https://github.com/gustafnk/h-include/ and made a few changes. I want to check with you @mnot that these changes are ok with you.

- Change name to h-include, to have separate name and follow custom element naming convention.
- I aim to publish h-include to npm, so I set the author field in package.json to myself and you @mnot as a collaborator.

Also, I'm clueless on how I should think about and act on the copyright line (Copyright (c) 2005-2012 Mark Nottingham <mnot@mnot.net>) in hinclude.js. I don't want to remove it, but should I just leave it as is and otherwise ignore it?

Cheers

**Comment by mnot** [comment]
Very cool!

Name seems fine to me. WRT copyright, I think the changes you've made are pretty substantial; feel free to remove it. If you want to keep it, just saying "based on..." is more than enough.

Tell me when it's ready and I'll point people to it.

**Comment by gustafnk** [comment]
It's ready and published to npm and bower :)

I kept your copyright line and added myself above it. In addition I linked to your repo in the readme.

Also, I improved the test stability and removed the python dependency with https://github.com/gustafnk/h-include/commit/c767587706065eba370dacc31e1b6619738cb9e4?w=1. I'll make a PR.

Here's my twitter, if you want to link to it: [@gustaf_nk](https://twitter.com/gustaf_nk)

Cheers

**Pull request closed without merging**
