### PR TITLE
Trigger event on load content

### PR DESCRIPTION
**Pull request by peter-gribanov**
Trigger event `hinclude` on load content.

Example:
```html
<hx:include src="container.html" id="hinclude_container"></hx:include>

<script type="text/javascript">
$('#hinclude_container').on('hinclude', function() {
    console.log('container is loaded');
});
</script>
```

### CODE REVIEW

**Comment by peter-gribanov** [comment]
I'm a back-end developer. I do not know how to write JavaScript tests.
If you help me, I can write tests.

**Comment by peter-gribanov** [comment]
I added test code

**Comment by mnot** [comment]
Looks really good, thanks. I'm going to leave this open for a couple of days, just to make sure that other peoples' use cases are met by it.

**Comment by Greibit** [comment]
It would be possible to create a new version tag with this feature?

**Comment by mnot** [comment]
Done. Thanks.

**Pull request merged**
